spring:    
  application:
    name: registration-service   #current service name to be used by the eureka server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8080